GET http://localhost:18000/api/article?page=1
Accept: application/json

###
// get blog list

GET http://localhost:18000/api/blog/606a5a3031fb4462f5438def
Accept: application/json

###
PUT http://localhost:18000/api/blog/606a5a3031fb4462f5438def
Accept: application/json
Content-Type: application/json

{
  "title": "博客标题",
  "description": "渐渐的说明",
  "small_cover": "https://dummyimage.com/200x200/000/fff",
  "big_cover": "https://dummyimage.com/1000x400/000/fff",
  "visible": true,
  "blog_type": 0,
  "tags": [
    "一个",
    "两个"
  ]
}

###
PUT http://localhost:18000/api/blog/606a5a3031fb4462f5438def
Accept: application/json
Content-Type: application/json

{
  "content": "# 快乐的假期",
  "HTML": "<h1>快乐的假期</h1>"
}

###
PUT http://localhost:18000/api/blog/606a586b31fb4462f5438dec?index=2
Accept: application/json
Content-Type: application/json

{
  "content": "你想要什么样的？",
  "HTML": "<h1>不对不对！</h1>"
}

###
POST http://localhost:18000/api/blog/60745e302cf90e40c8a49f1f
Accept: application/json
Content-Type: application/json

{
  "content": "你是不是喜欢伤害高的？？",
  "HTML": "<h1>你是不是喜欢伤害高的？？！</h1>"
}

###
DELETE http://localhost:18000/api/blog/60745bf90935842544416304?index=1
Accept: application/json
Content-Type: application/json

###
GET http://localhost:18000/api/total_page
Accept: application/json

###
GET http://localhost:18000/api/homepage?lang=zh
Accept: application/json

###
POST http://localhost:18001/api/bbs
Accept: application/json
Content-Type: application/json
Cookie: secret=abcdefg

{"content": "母亲节快乐", "issuer": "Neboer"}
###
GET http://localhost:18001/api/bbs?page=2
Accept: application/json

###
GET http://localhost:18001/api/bbs/pages
Accept: application/json

###
GET http://localhost:18001/wall?page=1
Accept: text/html
